pak::pak("jimbrig/gdalraster.windows")
gdalraster.windows::gdal_setup()
library(gdalraster)
gdalraster::gdal_version()
gdalraster::gdal_global_reg_names()
gdalraster.windows::gdal_sitrep()
gdalraster.windows::gdal_verify()
